using System.Text;
using System.Text.Json;
using ControlUp.Core.Models;
using Microsoft.Extensions.Logging;

namespace ControlUp.Core.Reporting;

/// <summary>
/// Implementation of report generator for market mover reports
/// </summary>
public class ReportGenerator : IReportGenerator
{
    private readonly ILogger<ReportGenerator> _logger;

    public ReportGenerator(ILogger<ReportGenerator> logger)
    {
        _logger = logger;
    }

    public async Task GenerateReportsAsync(
        MarketMoverReport report,
        string artifactsDirectory = "artifacts",
        CancellationToken cancellationToken = default)
    {
        // Ensure artifacts directory exists
        if (!Directory.Exists(artifactsDirectory))
        {
            Directory.CreateDirectory(artifactsDirectory);
            _logger.LogInformation("Created artifacts directory: {Directory}", artifactsDirectory);
        }

        // Generate JSON report
        await GenerateJsonReportAsync(report, artifactsDirectory, cancellationToken);

        // Generate Markdown report
        await GenerateMarkdownReportAsync(report, artifactsDirectory, cancellationToken);

        _logger.LogInformation("Reports generated successfully in {Directory}", artifactsDirectory);
    }

    private async Task GenerateJsonReportAsync(
        MarketMoverReport report,
        string artifactsDirectory,
        CancellationToken cancellationToken)
    {
        var jsonPath = Path.Combine(artifactsDirectory, "report.json");
        var options = new JsonSerializerOptions
        {
            WriteIndented = true
        };

        var json = JsonSerializer.Serialize(report, options);
        await File.WriteAllTextAsync(jsonPath, json, cancellationToken);

        _logger.LogInformation("JSON report written to {Path}", jsonPath);
    }

    private async Task GenerateMarkdownReportAsync(
        MarketMoverReport report,
        string artifactsDirectory,
        CancellationToken cancellationToken)
    {
        var mdPath = Path.Combine(artifactsDirectory, "report.md");
        var sb = new StringBuilder();

        sb.AppendLine("# Top Market Movers Report");
        sb.AppendLine();
        sb.AppendLine($"**Test Execution Time:** {report.TestExecutionTime:yyyy-MM-dd HH:mm:ss} UTC");
        sb.AppendLine($"**Generated At:** {report.GeneratedAt:yyyy-MM-dd HH:mm:ss} UTC");
        sb.AppendLine($"**Runtime:** {FormatRuntime(report.Runtime)}");
        sb.AppendLine();
        sb.AppendLine("## Top 3 Symbols by 24h Price Change");
        sb.AppendLine();
        sb.AppendLine("| Rank | Symbol | 24h Change % | Average Price |");
        sb.AppendLine("|------|--------|--------------|---------------|");

        foreach (var mover in report.TopMovers)
        {
            sb.AppendLine($"| {mover.Rank} | {mover.Symbol} | {mover.PriceChangePercent24Hr:F2}% | {mover.AveragePrice:F8} |");
        }

        sb.AppendLine();
        sb.AppendLine("---");
        sb.AppendLine($"*Report generated by ControlUp API Automation Framework*");

        await File.WriteAllTextAsync(mdPath, sb.ToString(), cancellationToken);

        _logger.LogInformation("Markdown report written to {Path}", mdPath);
    }

    private static string FormatRuntime(TimeSpan runtime)
    {
        if (runtime.TotalMilliseconds < 1000)
        {
            return $"{runtime.TotalMilliseconds:F0} ms";
        }
        else if (runtime.TotalSeconds < 60)
        {
            return $"{runtime.TotalSeconds:F2} seconds";
        }
        else
        {
            return $"{runtime.Minutes}m {runtime.Seconds}s {runtime.Milliseconds}ms";
        }
    }
}
